set(CAMERA_SRCS
    ../../../conversions/yuv.c
    ../../../conversions/to_jpg.cpp
    ../../../conversions/to_bmp.c
    ../../../conversions/jpge.cpp
    ../../../driver/esp_camera.c
    ../../../driver/esp_camera_af.c
    ../../../driver/cam_hal.c
    ../../../driver/sensor.c
    ../../../driver/sccb-ng.c
    ../../../sensors/ov2640.c
    ../../../sensors/ov3660.c
    ../../../sensors/ov3640.c
    ../../../sensors/ov5640.c
    ../../../sensors/ov5640_af.c
    ../../../sensors/ov7725.c
    ../../../sensors/ov7670.c
    ../../../sensors/nt99141.c
    ../../../sensors/gc0308.c
    ../../../sensors/gc2145.c
    ../../../sensors/gc032a.c
    ../../../sensors/bf3005.c
    ../../../sensors/bf20a6.c
    ../../../sensors/sc101iot.c
    ../../../sensors/sc030iot.c
    ../../../sensors/sc031gs.c
    ../../../sensors/mega_ccm.c
    ../../../sensors/hm1055.c
    ../../../sensors/hm0360.c
    ../../../target/xclk.c
    ../../../target/esp32/ll_cam.c
)

idf_component_register(
    SRCS main.c ${CAMERA_SRCS}
    INCLUDE_DIRS . ../../../driver/include ../../../conversions/include
    PRIV_INCLUDE_DIRS
        ../../../conversions/private_include
        ../../../driver/private_include
        ../../../sensors/private_include
        ../../../target/private_include
    REQUIRES
        driver
        freertos
        nvs_flash
        esp_mm
        esp_timer
        esp_psram
        esp_wifi
        esp_netif
        esp_event
        esp_http_server
        fatfs
        sdmmc
    PRIV_REQUIRES ""
)
